#
# ARC softmmu tests
#

ARC_SRC = $(SRC_PATH)/tests/tcg/arc
TEST_DIR = ${BUILD_DIR}/tests/tcg/${TARGET}

# ARC GENERIC (HS and HS5X)
ARC_GEN_SRC = ${ARC_SRC}/generic
ARC_GEN_FILES = $(filter-out $(ARC_GEN_SRC)/ivt.S,$(wildcard $(ARC_GEN_SRC)/*.S))
ARC_GEN_TESTS = $(patsubst $(ARC_GEN_SRC)/%.S, %_gen, $(ARC_GEN_FILES))

# ARC HS
ARC_HS_SRC = ${ARC_SRC}/hs
ARC_HS_FILES = $(wildcard $(ARC_HS_SRC)/*.S)
ARC_HS_TESTS = $(patsubst %, %_hs, $(ARC_GEN_TESTS))
ARC_HS_TESTS += $(patsubst $(ARC_HS_SRC)/%.S, %_hs, $(ARC_HS_FILES))
ARC_HS_ASFLAGS = -mcpu=archs
ARC_HS_CC = arc-elf32-gcc

# ARC HS5X
ARC_HS5X_SRC = ${ARC_SRC}/hs5x
ARC_HS5X_FILES = $(wildcard $(ARC_HS5X_SRC)/*.S)
ARC_HS5X_TESTS = $(patsubst %, %_hs5x, $(ARC_GEN_TESTS))
ARC_HS5X_TESTS += $(patsubst $(ARC_HS5X_SRC)/%.S, %_hs5x, $(ARC_HS5X_FILES))
ARC_HS5X_ASFLAGS = -mcpu=hs5x
ARC_HS5X_CC = arc64-elf-gcc

ARC_USABLE_TESTS = ${ARC_HS_TESTS} ${ARC_HS5X_TESTS}

# add to the list of tests
TESTS += $(ARC_USABLE_TESTS)
VPATH += $(ARC_SRC)

LDFLAGS = --specs=nsim.specs -T $(ARC_SRC)/tarc.ld -nostartfiles -nostdlib
CRT_HS = ivt_gen_hs.o
CRT_HS5X = ivt_gen_hs5x.o

$(ARC_USABLE_TESTS): $(CRT_HS) $(CRT_HS5X) Makefile.softmmu-target

%_gen_hs.o: generic/%.S 
	cd ${TEST_DIR} && \
	$(ARC_HS_CC) -I$(ARC_SRC) $($*ARC_HS_ASFLAGS) $(ARC_HS_ASFLAGS) $(EXTRACFLAGS) -c $< -o ./$@

%_gen_hs: %gen_hs.o
	cd ${TEST_DIR} && \
	$(ARC_HS_CC) -I$(ARC_SRC) $(ARC_HS_ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT_HS)

%_gen_hs5x.o: generic/%.S
	cd ${TEST_DIR} && \
	$(ARC_HS5X_CC) -I$(ARC_SRC) $($*ARC_HS5X_ASFLAGS) $(ARC_HS5X_ASFLAGS) $(EXTRACFLAGS) -c $< -o ./$@

%_gen_hs5x: %gen_hs5x.o
	cd ${TEST_DIR} && \
	$(ARC_HS5X_CC) -I$(ARC_SRC) $(ARC_HS5X_ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT_HS5X)

%_hs.o: hs/%.S
	cd ${TEST_DIR} && \
	$(ARC_HS_CC) -I$(ARC_SRC) $($*ARC_HS_ASFLAGS) $(ARC_HS_ASFLAGS) $(EXTRACFLAGS) -c $< -o ./$@

%_hs: %_hs.o
	cd ${TEST_DIR} && \
	$(ARC_HS_CC) -I$(ARC_SRC) $(ARC_HS_ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT_HS)

%_hs5x.o: hs5x/%.S
	cd ${TEST_DIR} && \
	$(ARC_HS5X_CC) -I$(ARC_SRC) $($*ARC_HS5X_ASFLAGS) $(ARC_HS5X_ASFLAGS) $(EXTRACFLAGS) -c $< -o ./$@

%_hs5x: %_hs5x.o
	cd ${TEST_DIR} && \
	$(ARC_HS5X_CC) -I$(ARC_SRC) $(ARC_HS5X_ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT_HS5X)

run-%_hs: QEMU_OPTS+=-M arc-sim -cpu archs -m 3G -nographic -no-reboot -serial stdio -global cpu.mpu-numreg=8 -kernel
run-%_hs5x: QEMU_OPTS+=-M arc-sim -cpu hs5x -m 3G -nographic -no-reboot -serial stdio -global cpu.mpu-numreg=8 -kernel
